# Список ошибок для исправления

## Бэкенд

### 1. Проблемы с Python 3.13
- Несовместимость SQLAlchemy с Python 3.13
```
AssertionError: Class <class 'sqlalchemy.sql.elements.SQLCoreOperations'> directly inherits TypingOnly but has additional attributes
```
- Несовместимость Pydantic с Python 3.13
```
TypeError: ForwardRef._evaluate() missing 1 required keyword-only argument: 'recursive_guard'
```

### 2. Проблемы с виртуальным окружением
- Не удается активировать venv311
```
Имя ".\venv311\Scripts\activate.ps1" не распознано как имя командлета
```
- Отсутствуют зависимости в окружении
```
ModuleNotFoundError: No module named 'fastapi'
```

### 3. Проблемы с зависимостями
- Конфликт версий в requirements.txt:
  - sqlalchemy==2.0.27 -> нужно понизить до 1.4.49
  - fastapi==0.104.1 -> нужно понизить до 0.95.2
  - pydantic требует обновления для работы с fastapi

## Фронтенд

### 1. Проблемы с API клиентом
- Несогласованность URL API:
  - В начале файла: `http://localhost:8000/api`
  - В конструкторе: `http://localhost:8000/api/v1`
- Отсутствует обработка токена авторизации в заголовках

### 2. Проблемы с отображением
- Не загружаются карточки аккаунтов
- Видны только поиск и надпись "Аккаунты" вверху

## План исправления

1. Бэкенд:
   - Установить Python 3.11
   - Создать новое виртуальное окружение
   - Обновить requirements.txt с совместимыми версиями
   - Переустановить зависимости

2. Фронтенд:
   - Исправить URL в API клиенте
   - Добавить обработку авторизации
   - Отладить загрузку и отображение данных

3. Общие задачи:
   - Проверить CORS настройки
   - Настроить логирование для отладки
   - Протестировать взаимодействие фронтенда с бэкендом 